// <auto-generated />
using Crud_API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_ProcessJudicial.Infra.Data.Migrations
{
    [DbContext(typeof(_DbContext))]
    [Migration("20231008011444_AlterColumnOab")]
    partial class AlterColumnOab
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("API_ProcessJudicial.Domain.Entities.Documents", b =>
                {
                    b.Property<long>("IdDocument")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("IdJudicialProcess")
                        .HasColumnType("bigint");

                    b.Property<long>("IdUsers")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdDocument");

                    b.HasIndex("IdJudicialProcess");

                    b.HasIndex("IdUsers");

                    b.ToTable("documents");
                });

            modelBuilder.Entity("API_ProcessJudicial.Domain.Entities.JudicialProcess", b =>
                {
                    b.Property<long>("IdJudicialProcess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Documents")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Part")
                        .HasColumnType("bigint");

                    b.Property<string>("ProcessNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Responsible")
                        .HasColumnType("bigint");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("ValueCause")
                        .HasColumnType("double");

                    b.HasKey("IdJudicialProcess");

                    b.ToTable("judicialprocesses");
                });

            modelBuilder.Entity("API_ProcessJudicial.Domain.Entities.Users", b =>
                {
                    b.Property<long>("IdUsers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAdvogado")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Oab")
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsers");

                    b.ToTable("users");
                });

            modelBuilder.Entity("API_ProcessJudicial.Domain.Entities.Documents", b =>
                {
                    b.HasOne("API_ProcessJudicial.Domain.Entities.JudicialProcess", "JudicialProcess")
                        .WithMany()
                        .HasForeignKey("IdJudicialProcess")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API_ProcessJudicial.Domain.Entities.Users", "user")
                        .WithMany()
                        .HasForeignKey("IdUsers")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JudicialProcess");

                    b.Navigation("user");
                });
#pragma warning restore 612, 618
        }
    }
}
